-- Generated by web/mkexamples.py from web/examples.json and the programs
-- in tests/. Edit those and run make, not this file.
module Examples (Example (..), examples) where

import Data.List (intercalate)

data Example = Example
  { exampleName  :: String
  , exampleDesc  :: String
  , exampleQuery :: String
  , exampleFiles :: [(String, String)]   -- ^ (name without .ttl, content)
  }

text :: [String] -> String
text = intercalate "\n"

examples :: [Example]
examples =
  [ Example
      { exampleName  = "Friendship network"
      , exampleDesc  = "Keeps only the foaf:knows triples of people.ttl by matching the predicate against an IRI. The result is the network of who knows whom."
      , exampleQuery = text
          [ "IMPORT people AS P;"
          , ""
          , "INTO out11 GET [subj,pred,obj] WHERE {P[subj,http://xmlns.com/foaf/0.1/knows,obj]};"
          , ""
          , "EXPORT out11;"
          , ""
          ]
      , exampleFiles = [("people", peopleTtl)]
      }
  , Example
      { exampleName  = "Adults, a year older"
      , exampleDesc  = "Comparisons only match numbers, so obj >= 18 picks out the adults' ages and skips the foaf:knows links. Their ages are written back one year older, and the ELSE IF branch marks the one person under 18 as a minor."
      , exampleQuery = text
          [ "IMPORT people AS P;"
          , ""
          , "IF {P[obj >= 18]} THEN"
          , "INTO out12 WRITETRUE {P[subj,pred,obj + 1]}"
          , "ELSE IF {P[obj < 18]} THEN"
          , "INTO out12 WRITETRUE {P[subj,http://example.org/people/minor,true]}"
          , "ELSE NOTHING;"
          , ""
          , "EXPORT out12;"
          , ""
          ]
      , exampleFiles = [("people", peopleTtl)]
      }
  , Example
      { exampleName  = "Pet owners"
      , exampleDesc  = "Joins two files. In the subject slot, obj IN Q keeps the people who appear as an object in pets.ttl, i.e. the pet owners, and pred is fixed to foaf:age. The second pattern adds every triple about the pets."
      , exampleQuery = text
          [ "IMPORT people AS P;"
          , "IMPORT pets AS Q;"
          , ""
          , "INTO out13 GET [subj,pred,obj] WHERE {P[obj IN Q,http://xmlns.com/foaf/0.1/age,obj] AND Q[subj,pred,obj]};"
          , ""
          , "EXPORT out13;"
          , ""
          ]
      , exampleFiles = [("people", peopleTtl), ("pets", petsTtl)]
      }
  , Example
      { exampleName  = "Merge two files"
      , exampleDesc  = "Gathers every triple of foo.ttl and bar.ttl into one file. Prefixed names and relative IRIs are resolved against @prefix and @base, and the output is sorted with duplicates removed."
      , exampleQuery = text
          [ "IMPORT foo AS A;"
          , "IMPORT bar AS B;"
          , ""
          , "INTO out1 GET [subj,pred,obj] WHERE {A[subj,pred,obj] AND B[subj,pred,obj]};"
          , ""
          , "EXPORT out1;"
          ]
      , exampleFiles = [("foo", fooTtl), ("bar", barTtl)]
      }
  , Example
      { exampleName  = "Match literal values"
      , exampleDesc  = "A literal in a WHERE pattern must match exactly: this keeps the triples whose subject is http://www.cw.org/#problem2 and whose object is true, including one written as the relative IRI <#problem2>."
      , exampleQuery = text
          [ "IMPORT foo AS A;"
          , ""
          , "INTO out2 GET [subj,pred,obj] WHERE {A[http://www.cw.org/#problem2,pred,true]};"
          , ""
          , "EXPORT out2;"
          ]
      , exampleFiles = [("foo", fooTtl)]
      }
  , Example
      { exampleName  = "Any of several predicates"
      , exampleDesc  = "Combines three WHERE patterns with OR to keep the triples whose predicate is one of three IRIs."
      , exampleQuery = text
          [ "IMPORT foo AS A;"
          , ""
          , "INTO out3 GET [subj,pred,obj] WHERE {A[subj,http://www.cw.org/problem3/#predicate1,obj]"
          , "              OR A[subj,http://www.cw.org/problem3/#predicate2,obj]"
          , "              OR A[subj,http://www.cw.org/problem3/#predicate3,obj]};"
          , ""
          , "EXPORT out3;"
          ]
      , exampleFiles = [("foo", fooTtl)]
      }
  , Example
      { exampleName  = "Link two files"
      , exampleDesc  = "subj IN B in the object slot keeps the triples of foo.ttl whose object is a subject in bar.ttl, and the second pattern does the same the other way round. The matches link up into a cycle."
      , exampleQuery = text
          [ "IMPORT foo AS A;"
          , "IMPORT bar AS B;"
          , ""
          , "INTO out4 GET [subj,pred,obj] WHERE {A[subj,pred,subj IN B] AND B[subj,pred,subj IN A]};"
          , ""
          , "EXPORT out4;"
          ]
      , exampleFiles = [("foo", fooTtl), ("bar", barTtl)]
      }
  , Example
      { exampleName  = "Conditional rewrite"
      , exampleDesc  = "An IF ... ELSE IF chain splits the numeric objects. Values outside 0-99 earn an inRange false triple; values inside are incremented by one and earn inRange true. Objects that are not numbers satisfy neither condition."
      , exampleQuery = text
          [ "IMPORT foo AS A;"
          , ""
          , "IF {A[obj < 0 OR obj > 99]} THEN"
          , "INTO out5 WRITETRUE {A[subj,http://www.cw.org/problem5/#inRange,false]}"
          , "ELSE IF {A[obj >= 0 AND obj <= 99]} THEN"
          , "INTO out5 WRITETRUE {A[subj,pred,obj + 1] AND A[subj,http://www.cw.org/problem5/#inRange,true]}"
          , "ELSE NOTHING;"
          , "EXPORT out5;"
          ]
      , exampleFiles = [("foo", fooTtl)]
      }
  , Example
      { exampleName  = "Turtle shorthand"
      , exampleDesc  = "baz.ttl abbreviates with prefixes, a predicate list (;) and an object list (,). Selecting every triple shows each one expanded into a full subject, predicate and object."
      , exampleQuery = text
          [ "IMPORT baz AS Z;"
          , ""
          , "INTO out6 GET [subj,pred,obj] WHERE {Z[subj,pred,obj]};"
          , ""
          , "EXPORT out6;"
          , ""
          ]
      , exampleFiles = [("baz", bazTtl)]
      }
  , Example
      { exampleName  = "Conditions over two files"
      , exampleDesc  = "Two IF statements write into the same file. The first keeps baz.ttl's objects between 10 and 20. The second also flags 50s in foo.ttl, but each file keeps its own flags, so writing from Z only adds baz.ttl's 1."
      , exampleQuery = text
          [ "IMPORT baz AS Z;"
          , "IMPORT foo AS A;"
          , ""
          , "IF {Z[obj >= 10] AND Z[obj <= 20]} THEN"
          , "INTO out7 WRITETRUE {Z[subj,pred,obj]}"
          , "ELSE NOTHING;"
          , ""
          , "IF {Z[obj = 1] OR A[obj = 50]} THEN"
          , "INTO out7 WRITETRUE {Z[subj,pred,obj]}"
          , "ELSE NOTHING;"
          , ""
          , "EXPORT out7;"
          , ""
          ]
      , exampleFiles = [("baz", bazTtl), ("foo", fooTtl)]
      }
  , Example
      { exampleName  = "FROM shorthand"
      , exampleDesc  = "GET ... FROM Z is shorthand for a WHERE block that matches every triple of Z."
      , exampleQuery = text
          [ "IMPORT baz AS Z;"
          , ""
          , "INTO out8 GET [subj,pred,obj] FROM Z;"
          , ""
          , "EXPORT out8;"
          , ""
          ]
      , exampleFiles = [("baz", bazTtl)]
      }
  , Example
      { exampleName  = "NOT and !="
      , exampleDesc  = "NOT binds tighter than AND, so this keeps the objects that are not greater than 10 and not equal to 1."
      , exampleQuery = text
          [ "IMPORT baz AS Z;"
          , ""
          , "IF {Z[NOT obj > 10 AND obj != 1]} THEN"
          , "INTO out9 WRITETRUE {Z[subj,pred,obj]}"
          , "ELSE NOTHING;"
          , ""
          , "EXPORT out9;"
          , ""
          ]
      , exampleFiles = [("baz", bazTtl)]
      }
  , Example
      { exampleName  = "Negative numbers"
      , exampleDesc  = "Negative integers work as literals and in conditions: the GET matches the object -50, and the IF adds a flag triple for every subject that has a negative object."
      , exampleQuery = text
          [ "IMPORT foo AS A;"
          , ""
          , "INTO out10 GET [subj,pred,obj] WHERE {A[subj,pred,-50]};"
          , ""
          , "IF {A[obj < 0]} THEN"
          , "INTO out10 WRITETRUE {A[subj,http://www.cw.org/neg/#flag,-1]}"
          , "ELSE NOTHING;"
          , ""
          , "EXPORT out10;"
          , ""
          ]
      , exampleFiles = [("foo", fooTtl)]
      }
  ]

peopleTtl :: String
peopleTtl = text
  [ "@prefix ex: <http://example.org/people/> ."
  , "@prefix foaf: <http://xmlns.com/foaf/0.1/> ."
  , ""
  , "ex:alice foaf:knows ex:bob ; foaf:knows ex:carol ; foaf:age 34 ."
  , "ex:bob foaf:knows ex:carol ; foaf:age 27 ."
  , "ex:carol foaf:knows ex:alice ; foaf:knows ex:dave ; foaf:age 41 ."
  , "ex:dave foaf:knows ex:erin ; foaf:age 17 ."
  , "ex:erin foaf:age 22 ."
  , ""
  ]

petsTtl :: String
petsTtl = text
  [ "@prefix ex: <http://example.org/people/> ."
  , "@prefix pet: <http://example.org/pets/> ."
  , ""
  , "pet:rex pet:ownedBy ex:alice ; pet:species pet:dog ."
  , "pet:tom pet:ownedBy ex:dave ; pet:species pet:cat ."
  , ""
  ]

fooTtl :: String
fooTtl = text
  [ "<http://www.cw.org/subjectA> <http://www.cw.org/predicateA> <http://www.cw.org/objectA> . "
  , ""
  , "@base <http://www.cw.org/> ."
  , ""
  , "<subjectB> <predicateB> <objectB> .         "
  , "@prefix p: <http://www.cw.org/pprefix/> ."
  , "p:subjectC p:predicateC p:objectC .    "
  , ""
  , "@prefix q: <http://www.cw.org/qprefix/> ."
  , "p:subjectD q:predicateD q:objectD .     "
  , ""
  , "@prefix r: <rprefix/> .                   "
  , "p:subjectE r:predicateE q:objectE .     "
  , ""
  , "<testSubA> <hasNegInt> -50 ."
  , "<testSubA> <hasPosInt> +50 ."
  , "<testSubA> <hasPosInt> 50 ."
  , "<testSubA> <hasBool> true ."
  , "<testSubA> <hasBool> false ."
  , "<testSubA> <hasStringLit> \"literalstring\" ."
  , ""
  , "<testSubA> <testPredList> -5 ; <testPredList> 10 ; <testPredList> 20 ."
  , ""
  , "<testSubA> <testObjList> -5 , 10 , 20 ."
  , ""
  , "<http://www.cw.org/#problem2> <testPredA> true ."
  , "<http://www.cw.org/#problem2> <testPredA> false ."
  , "<#problem2> <testPredB> true ."
  , "<#problemNot2> <testPredB> true ."
  , "<#problemNot2> <testPredB> false ."
  , ""
  , ""
  , "<testSubA><http://www.cw.org/problem3/#predicate1> true ."
  , "<testSubB><http://www.cw.org/problem3/#predicate2> true ."
  , "<testSubC><http://www.cw.org/problem3/#predicate3> true ."
  , "<testSubA><http://www.cw.org/problem3/#predicate4> true ."
  , "<testSubB><http://www.cw.org/problem3/#predicate5> true ."
  , "<testSubC><http://www.cw.org/problem3/#predicate6> true ."
  , "<testSubC><problem3/#predicate2> true ."
  , ""
  , ""
  , "<prob4A> <testPredA> <prob4B> ."
  , "<prob4C> <testPredB> <prob4D> ."
  , "<prob4E> <testPredC> <prob4F> ."
  , ""
  , ""
  ]

barTtl :: String
barTtl = text
  [ "<http://www.cw.org/subjectA> <http://www.cw.org/predicateA> <http://www.cw.org/objectA> . "
  , ""
  , "@base <http://www.cw.org/> ."
  , ""
  , "@prefix p: <http://www.cw.org/notpprefix/> ."
  , "p:subjectC p:predicateC p:objectC .    "
  , ""
  , "@prefix s: <http://www.cw.org/sprefix/> ."
  , "s:subjectD p:predicateD s:objectD .     "
  , ""
  , "@prefix t: <tprefix/> .                   "
  , "t:subjectE p:predicateE t:objectE .   "
  , ""
  , "<prob4B> <testPredA> <prob4C> ."
  , "<prob4D> <testPredB> <prob4E> ."
  , "<prob4F> <testPredC> <prob4A> ."
  , ""
  , ""
  , ""
  ]

bazTtl :: String
bazTtl = text
  [ "@base <http://www.cw.org/> ."
  , ""
  , "@prefix foaf: <http://xmlns.com/foaf/> ."
  , ""
  , "@prefix ex: <http://example.org/data/> ."
  , ""
  , "ex:alice foaf:name 1 ; foaf:age 30 ."
  , "ex:bob foaf:score 10 , 20 , 30 ."
  , "<plain> foaf:name 2 ."
  , ""
  ]
