#!/usr/bin/env python3
"""Generate web/Examples.hs from web/examples.json.

Each entry names a program under tests/ and gives it a title and a
description. The turtle files the program IMPORTs are bundled with it, read
from the program's own directory, so every example in the browser is exactly a
program that make test checks.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(HERE, 'Examples.hs')

# An IMPORT statement, with the file name matched the way Tokens.x lexes a var
IMPORT = re.compile(r"\bIMPORT\s+([A-Za-z][A-Za-z0-9:_'.$|*?#~^/]*)\s+AS\b")


def hs_string(s):
    """A Haskell string literal for s."""
    out = ['"']
    numeric = False                 # did the last escape end in a digit?
    for ch in s:
        code = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '\t':
            out.append('\\t')
        elif 32 <= code < 127:
            out.append('\\&' + ch if numeric and ch.isdigit() else ch)
        else:
            out.append('\\%d' % code)
            numeric = True
            continue
        numeric = False
    out.append('"')
    return ''.join(out)


def hs_lines(text, indent):
    """text as `text [..]`, one line per list element, so it reads like the file."""
    lines = text.split('\n')
    pad = ' ' * indent
    body = ('\n' + pad + ', ').join(hs_string(line) for line in lines)
    return 'text\n' + pad + '[ ' + body + '\n' + pad + ']'


def identifier(name):
    """The Haskell binding that holds the content of name.ttl."""
    words = re.split(r'[^A-Za-z0-9]+', name)
    return words[0][:1].lower() + words[0][1:] + ''.join(w.capitalize() for w in words[1:]) + 'Ttl'


def main():
    with open(os.path.join(HERE, 'examples.json')) as f:
        manifest = json.load(f)

    files = {}                      # file name -> content, in order of first use
    examples = []
    for entry in manifest:
        path = os.path.join(ROOT, entry['program'])
        with open(path) as f:
            program = f.read()
        code = '\n'.join(line.split('--')[0] for line in program.split('\n'))
        imports = list(dict.fromkeys(IMPORT.findall(code)))
        for name in imports:
            if name not in files:
                with open(os.path.join(os.path.dirname(path), name + '.ttl')) as f:
                    files[name] = f.read()
        examples.append((entry, program, imports))

    out = [
        '-- Generated by web/mkexamples.py from web/examples.json and the programs',
        '-- in tests/. Edit those and run make, not this file.',
        'module Examples (Example (..), examples) where',
        '',
        'import Data.List (intercalate)',
        '',
        'data Example = Example',
        '  { exampleName  :: String',
        '  , exampleDesc  :: String',
        '  , exampleQuery :: String',
        '  , exampleFiles :: [(String, String)]   -- ^ (name without .ttl, content)',
        '  }',
        '',
        'text :: [String] -> String',
        'text = intercalate "\\n"',
        '',
        'examples :: [Example]',
        'examples =',
    ]
    for i, (entry, program, imports) in enumerate(examples):
        lead = '  [ ' if i == 0 else '  , '
        bundled = ', '.join('(%s, %s)' % (hs_string(n), identifier(n)) for n in imports)
        out += [
            lead + 'Example',
            '      { exampleName  = ' + hs_string(entry['name']),
            '      , exampleDesc  = ' + hs_string(entry['description']),
            '      , exampleQuery = ' + hs_lines(program, 10),
            '      , exampleFiles = [' + bundled + ']',
            '      }',
        ]
    out += ['  ]', '']
    for name, content in files.items():
        out += [identifier(name) + ' :: String',
                identifier(name) + ' = ' + hs_lines(content, 2), '']

    with open(OUT, 'w') as f:
        f.write('\n'.join(out))


if __name__ == '__main__':
    main()
