{-# LANGUAGE OverloadedStrings #-}
module Styles (appCSS) where

import Miso.String (MisoString)

import Format (str)

-- | The stylesheet, injected as a <style> element. Layout, colours and the
--   mobile breakpoint follow the Terrible Tiling Toolkit.
appCSS :: MisoString
appCSS = str $ unlines
  [ "* { box-sizing: border-box; margin: 0; }"
  , "body { margin: 0; padding: 0; overflow-x: hidden; }"
  , "@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }"
  , ""
  , "/* Two panels side by side */"
  , ".stql-container { display: flex; flex-direction: row; font-family: Arial, sans-serif; height: 100vh; }"
  , ".stql-editor { width: 50%; padding: 20px; background-color: #f7f7f7;"
  , "  box-shadow: 2px 0px 5px rgba(0,0,0,0.1); overflow-y: auto; }"
  , ".stql-output { width: 50%; padding: 20px; display: flex; flex-direction: column; min-width: 0; }"
  , ""
  , "/* Left panel */"
  , ".about h1 { color: #222; margin-bottom: 2px; font-size: 22px; }"
  , ".about .tagline { color: #444; font-size: 14px; margin-bottom: 12px; }"
  , ".about p { color: #666; font-size: 13px; line-height: 1.5; margin-bottom: 16px; }"
  , ".about a { color: #2980b9; text-decoration: none; }"
  , ".about a.paper-link { cursor: pointer; border-bottom: 1px dashed #2980b9; }"
  , ".stql-editor hr { border: none; border-top: 1px solid #ddd; margin-bottom: 16px; }"
  , ".stql-editor h2 { color: #333; margin-top: 20px; margin-bottom: 10px; font-size: 18px; }"
  , ".dropdown { width: 100%; padding: 10px; margin-bottom: 20px; font-size: 16px;"
  , "  border: 1px solid #ccc; border-radius: 4px; background: #fff; }"
  , ".desc { color: #555; font-size: 13px; line-height: 1.4; margin-top: -12px; margin-bottom: 4px;"
  , "  padding: 8px 12px; background-color: #eef4fb; border-radius: 4px; border-left: 3px solid #3498db; }"
  , ""
  , "/* Code editors: a highlighted <pre> under a transparent <textarea>. The"
  , "   outer box scrolls both; the grid keeps them the same size. */"
  , ".code-box { width: 100%; overflow: auto; border: 1px solid #444; border-radius: 4px;"
  , "  background-color: #1e1e1e; }"
  , ".query-box { height: 200px; margin-bottom: 16px; }"
  , ".file-box { height: 160px; }"
  , ".code-grid { display: grid; min-height: 100%; }"
  , ".code-grid > pre, .code-grid > textarea { grid-row: 1; grid-column: 1; margin: 0; padding: 10px;"
  , "  font-family: monospace; font-size: 14px; line-height: 1.4; white-space: pre-wrap;"
  , "  word-wrap: break-word; overflow: hidden; box-sizing: border-box; background: transparent;"
  , "  border: none; tab-size: 4; }"
  , ".file-box .code-grid > pre, .file-box .code-grid > textarea { font-size: 13px; }"
  , ".code-grid > pre { color: #d4d4d4; pointer-events: none; }"
  , ".code-grid > textarea { color: transparent; caret-color: #d4d4d4; resize: none; outline: none;"
  , "  -webkit-text-fill-color: transparent; }"
  , ".code-grid > textarea::selection { background: rgba(38, 79, 120, 0.9); }"
  , ""
  , ".btn, .btn-small, .btn-remove { color: white; border: none; border-radius: 4px; cursor: pointer;"
  , "  touch-action: manipulation; font-family: Arial, sans-serif; }"
  , ".btn { padding: 12px 18px; font-size: 16px; background-color: #3498db; }"
  , ".btn-small { padding: 8px 14px; font-size: 16px; background-color: #3498db; }"
  , ".btn-remove { padding: 8px 14px; font-size: 14px; background-color: #e74c3c; }"
  , ".btn:hover, .btn-small:hover { background-color: #2e86c1; }"
  , ".btn-remove:hover { background-color: #cf3f30; }"
  , ".run-row { display: flex; align-items: center; gap: 12px; flex-wrap: wrap; }"
  , ".hint { color: #888; font-size: 13px; }"
  , ""
  , ".file-card { margin-bottom: 10px; padding: 8px; background-color: #fff; border: 1px solid #ddd;"
  , "  border-radius: 4px; }"
  , ".file-head { display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap;"
  , "  gap: 8px; margin-bottom: 8px; }"
  , ".file-name { font-family: monospace; font-size: 15px; font-weight: bold; color: #333; word-break: break-all; }"
  , ".file-meta { font-family: Arial, sans-serif; font-size: 12px; font-weight: normal; color: #888; margin-left: 8px; }"
  , ".note { color: #888; font-size: 13px; margin-bottom: 10px; }"
  , ".add-row { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 8px; }"
  , ".text-input { padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 4px;"
  , "  flex: 1; min-width: 100px; }"
  , ".new-file-body { width: 100%; min-height: 110px; padding: 10px; font-family: monospace; font-size: 13px;"
  , "  border: 1px solid #ccc; border-radius: 4px; resize: vertical; }"
  , ".form-error { color: #c0392b; font-size: 13px; margin-top: 6px; }"
  , ".add-file { margin-bottom: 20px; }"
  , ""
  , "/* Right panel */"
  , ".output-toolbar { display: flex; justify-content: space-between; align-items: center;"
  , "  margin-bottom: 8px; flex-wrap: wrap; gap: 8px; }"
  , ".output-toolbar h1 { color: #333; }"
  , ".modes { display: inline-flex; border: 1px solid #3498db; border-radius: 4px; overflow: hidden; }"
  , ".modes button { padding: 8px 14px; font-size: 14px; border: none; background: #fff; color: #3498db;"
  , "  cursor: pointer; font-family: Arial, sans-serif; touch-action: manipulation; }"
  , ".modes button + button { border-left: 1px solid #3498db; }"
  , ".modes button.active { background: #3498db; color: #fff; }"
  , ".output-main { flex: 1; display: flex; flex-direction: column; min-height: 0; }"
  , ".output-bar { display: flex; justify-content: space-between; align-items: flex-end;"
  , "  flex-wrap: wrap; gap: 8px; margin-bottom: 8px; }"
  , ".tabs { display: flex; flex-wrap: wrap; gap: 4px; }"
  , ".tab { padding: 6px 10px; font-size: 14px; font-family: monospace; color: #777; cursor: pointer;"
  , "  background: none; border: none; border-bottom: 3px solid transparent; }"
  , ".tab.active { color: #222; font-weight: bold; border-bottom-color: #3498db; }"
  , ".tab .count { font-family: Arial, sans-serif; font-size: 12px; font-weight: normal; color: #999; margin-left: 6px; }"
  , ".actions { display: flex; align-items: center; gap: 6px; }"
  , ".zoom-level { font-size: 13px; color: #888; }"
  , ".download { font-size: 14px; color: #2980b9; text-decoration: none; padding: 8px 12px;"
  , "  border: 1px solid #2980b9; border-radius: 4px; }"
  , ".download:hover { background: #eef4fb; }"
  , ".output-box { flex: 1; position: relative; min-height: 300px; overflow: hidden;"
  , "  border: 1px solid #ccc; border-radius: 6px; background-color: #fafafa; }"
  , ".output-box.scroll { overflow: auto; }"
  , ".output-box.dark { background-color: #1e1e1e; border-color: #444; }"
  , ".message { position: absolute; top: 0; left: 0; right: 0; bottom: 0; display: flex;"
  , "  flex-direction: column; justify-content: center; align-items: center; text-align: center;"
  , "  padding: 24px; color: #666; font-size: 14px; line-height: 1.5; }"
  , ".message h3 { color: #333; font-size: 16px; margin-bottom: 6px; }"
  , ".spinner { width: 40px; height: 40px; border: 4px solid #e0e0e0; border-top: 4px solid #3498db;"
  , "  border-radius: 50%; animation: spin 0.8s linear infinite; margin-bottom: 16px; }"
  , ".error-box { margin: 16px; padding: 12px 16px; border-left: 4px solid #e74c3c;"
  , "  background: #fdecea; border-radius: 4px; }"
  , ".error-box h3 { color: #c0392b; font-size: 15px; margin-bottom: 6px; }"
  , ".error-box pre { font-family: monospace; font-size: 14px; color: #333; white-space: pre-wrap;"
  , "  word-break: break-word; }"
  , ""
  , "/* Graph view: pointer events stop at the viewport, so offsets are its own */"
  , ".stql-viewport { position: absolute; top: 0; left: 0; right: 0; bottom: 0; overflow: hidden;"
  , "  user-select: none; touch-action: none; }"
  , ".stql-viewport-inner { width: 100%; height: 100%; transform-origin: 50% 50%;"
  , "  pointer-events: none; }"
  , ".stql-graph .g-edge { fill: none; stroke: #8a99a8; stroke-width: 1.3; }"
  , ".stql-graph .g-head { fill: #8a99a8; }"
  , ".stql-graph text { font-family: monospace; font-size: 12px; text-anchor: middle; dominant-baseline: central; }"
  , ".stql-graph .g-iri rect { fill: #eaf2fb; stroke: #3498db; stroke-width: 1.3; }"
  , ".stql-graph .g-iri text { fill: #1f4e79; }"
  , ".stql-graph .g-lit rect { fill: #fef5e7; stroke: #f0b35a; stroke-width: 1.3; }"
  , ".stql-graph .g-lit text { fill: #7e5109; }"
  , ".stql-graph .g-label { font-size: 11px; fill: #555; dominant-baseline: auto; paint-order: stroke;"
  , "  stroke: #fafafa; stroke-width: 4px; stroke-linejoin: round; }"
  , ""
  , "/* Table view */"
  , ".triples { width: 100%; border-collapse: collapse; font-size: 13px; }"
  , ".triples th { position: sticky; top: 0; text-align: left; padding: 8px 10px; color: #333;"
  , "  background: #eef1f5; border-bottom: 1px solid #d5dbe3; font-family: Arial, sans-serif; }"
  , ".triples td { padding: 6px 10px; border-bottom: 1px solid #eee; font-family: monospace;"
  , "  vertical-align: top; word-break: break-all; }"
  , ".triples tr:nth-child(even) td { background: #f3f5f8; }"
  , ".triples .row-num { color: #aaa; width: 1%; text-align: right; white-space: nowrap; }"
  , ".v-iri { color: #1f4e79; } .v-num { color: #098658; } .v-bool { color: #0000ff; } .v-str { color: #a31515; }"
  , ""
  , "/* Turtle view */"
  , ".turtle-view { margin: 0; padding: 12px; font-family: monospace; font-size: 13px; line-height: 1.5;"
  , "  color: #d4d4d4; white-space: pre; }"
  , ""
  , "/* Syntax colours */"
  , ".t-kw { color: #569cd6; } .t-ctl { color: #c586c0; } .t-pos { color: #dcdcaa; }"
  , ".t-bool { color: #569cd6; } .t-num { color: #b5cea8; } .t-iri { color: #4ec9b0; }"
  , ".t-var { color: #9cdcfe; } .t-op { color: #d4d4d4; } .t-punct { color: #808080; }"
  , ".t-com { color: #6a9955; } .t-dir { color: #c586c0; } .t-str { color: #ce9178; }"
  , ".t-pname { color: #9cdcfe; }"
  , ".t-err { color: #f44747; text-decoration: underline wavy #f44747; }"
  , ""
  , "/* The report, over everything */"
  , ".paper-overlay { position: fixed; top: 0; left: 0; width: 100vw; height: 100vh; z-index: 9999;"
  , "  background-color: rgba(0,0,0,0.7); display: flex; flex-direction: column;"
  , "  align-items: center; justify-content: center; font-family: Arial, sans-serif; }"
  , ".paper-bar { width: 90%; max-width: 900px; display: flex; justify-content: space-between;"
  , "  align-items: center; gap: 8px; margin-bottom: 8px; }"
  , ".paper-bar span { color: #fff; font-size: 16px; }"
  , ".paper-bar a { color: #fff; font-size: 14px; text-decoration: none; padding: 6px 14px;"
  , "  border: 1px solid #fff; border-radius: 4px; }"
  , ".paper-bar button { padding: 6px 14px; background-color: #e74c3c; color: white; border: none;"
  , "  border-radius: 4px; cursor: pointer; font-size: 14px; }"
  , ".paper-frame { width: 90%; max-width: 900px; height: 85vh; border: none; border-radius: 6px;"
  , "  background-color: #fff; }"
  , ""
  , "/* Mobile: stack the panels */"
  , "@media (max-width: 768px) {"
  , "  .stql-container { flex-direction: column; height: auto; min-height: 100vh; }"
  , "  .stql-editor { width: 100%; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }"
  , "  .stql-output { width: 100%; min-height: 85vh; }"
  , "  .output-toolbar h1 { font-size: 26px; }"
  , "}"
  ]
